[package]
name = "rcss"
version = "0.0.0"
edition = "2021"
description = "Rust simplified CSS parser implemented on top of proc-macro::TokenStreams"
authors = ["vldm <me@vldm.cc>"]
keywords = ["css", "html", "rsx", "macro", "parse"]
repository = "https://github.com/rs-tml/rcss"
# readme = "README.md"
license = "MIT"
resolver = "2"
# include = ["/src", "LICENSE"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = { version = "1.0.69", features = ["span-locations"] }
quote = "1.0.21"
syn = { version = "2.0.15", features = ["full", "parsing", "extra-traits"] }
thiserror = "1.0.37"
syn_derive = "0.1.6"
proc-macro2-diagnostics = { version = "0.10", default-features = false }
derive-where = "1.2.5"
rstml = { path = "../rstml", features = ["rawtext-stable-hack-module"] }

[dev-dependencies]
pretty_assertions = "1.4"
