name: bench

on: [pull_request]

jobs:
  bench:
    name: bench
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: critcmp
        run: |
          cargo install critcmp
          cargo bench -p rcss-core -- --save-baseline changes
          git checkout main
          cargo bench -p rcss-core -- --save-baseline main
          critcmp main changes
