name: ci

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: fmt
        run: cargo +nightly fmt --all -- --check

      - uses: dtolnay/rust-toolchain@stable
      - name: Stable test
        run: cargo test --workspace --exclude build_rs_test

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Install all-features
        run: cargo install cargo-all-features
      - name: Install cargo-expand for tests
        run: cargo install cargo-expand

      - name: Nightly test all backends
        run: cargo test-all-features

      - name: clippy
        run: cargo clippy --workspace

      - name: coverage
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --out xml
          bash <(curl -s https://codecov.io/bash)
